package com.car.model;

import java.io.Serializable;

/**
 * Car 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Car implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** CarID. */
	private String carid;

	/** brand. */
	private String brand;

	/** color. */
	private String color;

	/** price. */
	private Double price;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Car() {
	}

	/**
	 * CarID 傪愝掕偟傑偡.
	 * 
	 * @param carid
	 *            CarID
	 */
	public void setCarid(String carid) {
		this.carid = carid;
	}

	/**
	 * CarID 傪庢摼偟傑偡.
	 * 
	 * @return CarID
	 */
	public String getCarid() {
		return this.carid;
	}

	/**
	 * brand 傪愝掕偟傑偡.
	 * 
	 * @param brand
	 *            brand
	 */
	public void setBrand(String brand) {
		this.brand = brand;
	}

	/**
	 * brand 傪庢摼偟傑偡.
	 * 
	 * @return brand
	 */
	public String getBrand() {
		return this.brand;
	}

	/**
	 * color 傪愝掕偟傑偡.
	 * 
	 * @param color
	 *            color
	 */
	public void setColor(String color) {
		this.color = color;
	}

	/**
	 * color 傪庢摼偟傑偡.
	 * 
	 * @return color
	 */
	public String getColor() {
		return this.color;
	}

	/**
	 * price 傪愝掕偟傑偡.
	 * 
	 * @param price
	 *            price
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * price 傪庢摼偟傑偡.
	 * 
	 * @return price
	 */
	public Double getPrice() {
		return this.price;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((carid == null) ? 0 : carid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Car other = (Car) obj;
		if (carid == null) {
			if (other.carid != null) {
				return false;
			}
		} else if (!carid.equals(other.carid)) {
			return false;
		}

		return true;
	}

}
