package com.car.model;

import java.io.Serializable;

/**
 * News 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class News implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** newid. */
	private String newid;

	/** content. */
	private String content;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public News() {
	}

	/**
	 * newid 傪愝掕偟傑偡.
	 * 
	 * @param newid
	 *            newid
	 */
	public void setNewid(String newid) {
		this.newid = newid;
	}

	/**
	 * newid 傪庢摼偟傑偡.
	 * 
	 * @return newid
	 */
	public String getNewid() {
		return this.newid;
	}

	/**
	 * content 傪愝掕偟傑偡.
	 * 
	 * @param content
	 *            content
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * content 傪庢摼偟傑偡.
	 * 
	 * @return content
	 */
	public String getContent() {
		return this.content;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((newid == null) ? 0 : newid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		News other = (News) obj;
		if (newid == null) {
			if (other.newid != null) {
				return false;
			}
		} else if (!newid.equals(other.newid)) {
			return false;
		}

		return true;
	}

}
